[package]
name = "rmd"
version = "0.1.0"
authors = ["Santiago Narvaez <santiago.narvaez@tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_approx_eq = "1.1.0"
